// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20190408210407_RemovedCostumerTable")]
    partial class RemovedCostumerTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataLayer.Entities.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            Name = "Ralph Lauren"
                        },
                        new
                        {
                            BrandId = 2,
                            Name = "Tommy Hilfiger"
                        },
                        new
                        {
                            BrandId = 3,
                            Name = "Nike"
                        },
                        new
                        {
                            BrandId = 4,
                            Name = "Hugo Boss"
                        },
                        new
                        {
                            BrandId = 5,
                            Name = "Burberry"
                        },
                        new
                        {
                            BrandId = 6,
                            Name = "Levi Strauss & Co."
                        },
                        new
                        {
                            BrandId = 7,
                            Name = "Gucci"
                        },
                        new
                        {
                            BrandId = 8,
                            Name = "Lacoste"
                        },
                        new
                        {
                            BrandId = 9,
                            Name = "Adidas"
                        },
                        new
                        {
                            BrandId = 10,
                            Name = "Versace"
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Accessories"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Jackets"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Trousers"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Underwear"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Suits"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Skirts and dresses"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Shoes"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Sweaters and hoodies"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "T-Shirts"
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Clothing", b =>
                {
                    b.Property<int>("ClothingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Color");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("FKBrandId");

                    b.Property<int>("FKCategoryId");

                    b.Property<int>("FKImageId");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("Size");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("ClothingId");

                    b.HasIndex("FKBrandId");

                    b.HasIndex("FKCategoryId");

                    b.HasIndex("FKImageId");

                    b.ToTable("Clothing");

                    b.HasData(
                        new
                        {
                            ClothingId = 1,
                            Color = 1,
                            Description = "Sort Ralph Lauren Polo",
                            FKBrandId = 1,
                            FKCategoryId = 9,
                            FKImageId = 1,
                            Price = 25m,
                            Size = 2,
                            Title = "Sort Ralph Lauren Polo"
                        },
                        new
                        {
                            ClothingId = 2,
                            Color = 4,
                            Description = "Grøn Ralph Lauren Polo",
                            FKBrandId = 1,
                            FKCategoryId = 9,
                            FKImageId = 2,
                            Price = 25m,
                            Size = 2,
                            Title = "Grøn Ralph Lauren Polo"
                        },
                        new
                        {
                            ClothingId = 3,
                            Color = 3,
                            Description = "Rød Ralph Lauren Polo",
                            FKBrandId = 1,
                            FKCategoryId = 9,
                            FKImageId = 3,
                            Price = 25m,
                            Size = 2,
                            Title = "Rød Ralph Lauren Polo"
                        },
                        new
                        {
                            ClothingId = 4,
                            Color = 5,
                            Description = "Blå Ralph Lauren Polo",
                            FKBrandId = 1,
                            FKCategoryId = 9,
                            FKImageId = 4,
                            Price = 25m,
                            Size = 2,
                            Title = "Blå Ralph Lauren Polo"
                        },
                        new
                        {
                            ClothingId = 5,
                            Color = 6,
                            Description = "Gule Hugo Boss Underbukser",
                            FKBrandId = 4,
                            FKCategoryId = 4,
                            FKImageId = 5,
                            Price = 5m,
                            Size = 3,
                            Title = "Gule Hugo Boss Underbukser"
                        },
                        new
                        {
                            ClothingId = 6,
                            Color = 2,
                            Description = "Hvide Hugo Boss Underbukser",
                            FKBrandId = 4,
                            FKCategoryId = 4,
                            FKImageId = 6,
                            Price = 5m,
                            Size = 3,
                            Title = "Hvide Hugo Boss Underbukser"
                        },
                        new
                        {
                            ClothingId = 7,
                            Color = 3,
                            Description = "Røde Hugo Boss Underbukser",
                            FKBrandId = 4,
                            FKCategoryId = 4,
                            FKImageId = 7,
                            Price = 5m,
                            Size = 3,
                            Title = "Røde Hugo Boss Underbukser"
                        },
                        new
                        {
                            ClothingId = 8,
                            Color = 5,
                            Description = "Blå Hugo Boss Underbukser",
                            FKBrandId = 4,
                            FKCategoryId = 4,
                            FKImageId = 8,
                            Price = 5m,
                            Size = 3,
                            Title = "Blå Hugo Boss Underbukser"
                        },
                        new
                        {
                            ClothingId = 9,
                            Color = 4,
                            Description = "Grønne bukser",
                            FKBrandId = 2,
                            FKCategoryId = 3,
                            FKImageId = 9,
                            Price = 20m,
                            Size = 1,
                            Title = "Tommy Hilfinger Bukser"
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Costumer", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<int>("PaymentMethod");

                    b.HasKey("Name");

                    b.ToTable("Costumer");
                });

            modelBuilder.Entity("DataLayer.Entities.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AltText")
                        .IsRequired();

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("ImageId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            ImageId = 1,
                            AltText = "Sort Ralph Lauren Polo",
                            Url = "Images/SortRalphLaurenPolo.jpg"
                        },
                        new
                        {
                            ImageId = 2,
                            AltText = "Grøn Ralph Lauren Polo",
                            Url = "Images/GrønRalphLaurenPolo.jpg"
                        },
                        new
                        {
                            ImageId = 3,
                            AltText = "Rød Ralph Lauren Polo",
                            Url = "Images/RødRalphLaurenPolo.jpg"
                        },
                        new
                        {
                            ImageId = 4,
                            AltText = "Blå Ralph Lauren Polo",
                            Url = "Images/BlåRalphLaurenPolo.jpg"
                        },
                        new
                        {
                            ImageId = 5,
                            AltText = "Gule Hugo Boss Underbukser",
                            Url = "Images/GuleHugoBossUnderbukser.jpg"
                        },
                        new
                        {
                            ImageId = 6,
                            AltText = "Hvide Hugo Boss Underbukser",
                            Url = "Images/HvideHugoBossUnderbukser.jpg"
                        },
                        new
                        {
                            ImageId = 7,
                            AltText = "Røde Hugo Boss Underbukser",
                            Url = "Images/RødeHugoBossUnderbukser.jpg"
                        },
                        new
                        {
                            ImageId = 8,
                            AltText = "Blå Hugo Boss Underbukser",
                            Url = "Images/BlåHugoBossUnderbukser.jpg"
                        },
                        new
                        {
                            ImageId = 9,
                            AltText = "Tommy Hilfinger Bukser",
                            Url = "Images/GrønneTommyHilfingerBukser.jpg"
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CostumerName");

                    b.Property<DateTime>("Date");

                    b.Property<string>("FKCostumerId")
                        .IsRequired();

                    b.HasKey("OrderId");

                    b.HasIndex("CostumerName");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DataLayer.Entities.OrderLine", b =>
                {
                    b.Property<int>("FKClothingId");

                    b.Property<int>("FKOrderId");

                    b.Property<int>("Amount");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("FKClothingId", "FKOrderId");

                    b.HasIndex("FKOrderId");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("DataLayer.Entities.Clothing", b =>
                {
                    b.HasOne("DataLayer.Entities.Brand", "Brand")
                        .WithMany("Clothing")
                        .HasForeignKey("FKBrandId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataLayer.Entities.Category", "Category")
                        .WithMany("Clothing")
                        .HasForeignKey("FKCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataLayer.Entities.Image", "Image")
                        .WithMany("Clothing")
                        .HasForeignKey("FKImageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataLayer.Entities.Order", b =>
                {
                    b.HasOne("DataLayer.Entities.Costumer", "Costumer")
                        .WithMany("Orders")
                        .HasForeignKey("CostumerName");
                });

            modelBuilder.Entity("DataLayer.Entities.OrderLine", b =>
                {
                    b.HasOne("DataLayer.Entities.Clothing", "Clothing")
                        .WithMany("OrderLines")
                        .HasForeignKey("FKClothingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataLayer.Entities.Order", "Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("FKOrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
